### ISSUE TITLE
Can't change status from Homekit

### ISSUE THREAD

**Issue by Louison-B** [martinbernat/homebridge-th16ermostat#4]
I can't change status from Homekit since the last update (no respond). But I can change status with the Homebridge UI web interface (accessories tab).

**Comment by martinbernat** [comment]
Do you have the "sensorName" set in your config? Since last update it is mandatory parameter. Check the Configuration part of README file please. Let me know if it helps.

**Comment by Louison-B** [comment]
Yeah I see that. I have configure my sensor : SI7021. I can have the actual temp but I can't change "Off", "Heat" or "auto" status in Homekit iOS app. But I can change "Off", "Heat" or "auto" status in Homebridge UI web interface.

**Comment by Louison-B** [comment]
I try with my Mac and Homekit work perfectly with the Sonoff TH. I restart my iPhone and same problem no respond with the Sonoff TH...

**Comment by martinbernat** [comment]
Well, trying to reproduce the issue but no luck so far. Everything works as expected on my side (iPhone/14.3, Mac/BigSur). I suppose it won't be a configuration error since you wrote that it works fine in HomebridgeUI. Also the Home app should be configured correctly (works fine on Mac). Not sure what to recommend, sorry. Please post screenshots, config, ... Maybe we'll find out something.

**Comment by Louison-B** [comment]
I don't understand why but now it's work with my iPhone ... Sorry for the false alarm ...
I had the error that with your plugin so I thought the error was from this one.
